<?php

#@author David González Conejero

$a = 23;
$b = "pepe";
//probando el operador ++;
print_r("Probando el operador ++<br>");
echo "Aquí solamente incrementamos en 1 el valor de la variable<br>";
echo ++$a;
echo "<br>";
echo "Aquí incrementamos en otro el valor de la variable y, además, después la multiplica por 2<br>";
echo ++$a * 2;
echo "<br>";
echo "Aquí incrementa en 1 el valor de la variable nuevamente, pero como no es numérica, nos pone la siguiente letra del abecedario (en este caso la 'f')<br>";
echo ++$b;
echo "<br>";
echo "Ahora incrementamos en 1 el valor de la variable, pero al multiplicar un string nos devolverá '0'<br>";
echo ++$b * 2;
echo "<br><br>";
//probando el operador --;
print_r("Probando el operador --<br>");
echo "Ahora restamos 1 a la variable 'a' que estaba en 24 tras el último cambio de arriba y multiplicamos x 2<br>";
echo --$a * 2;
echo "<br>Ahora volvemos a asignar el valor original a la variable 'b' y le restamos 1, pero no tiene ningún efecto(solo si incrementamos)<br>";
$b = "pepe";
echo --$b;
echo "<br><br>";
//probando el operador +=n;
print_r("Probando el operador +=n");
echo "<br>Ahora le sumamos 5 a la variable 'a', que había quedado en 24<br>";
echo $a += 5;
echo "<br>Ahora multiplicamos 2 por el resultado de 'a' + 5<br>";
echo 2 * $a += 5;
echo "<br>Aquí como ya habíamos incrementado en 5 el valor de 'a', al multiplicar por 2 obtenemos el mismo resultado de antes<br>";
echo 2 * $a;
echo "<br>Al incrementar 5 un string (la variable 'b'), toma de valor de inicio 0, por lo que el resultado será:<br>";
echo $b += 5;
echo "<br>Ahora incrementamos nuevamente el 5 la variable 'b' que valía 5, y ese resultado lo multiplica x 2<br>";
echo 2 * $b += 5;
echo "<br>Como ya hemos incrementado en 5 el valor de'b', al multiplicar x 2 obtenemos el mismo resultado<br>";
echo 2 * $b;
echo "<br><br>";
//probando el operador –=n;
print_r("Probando el operador -=n");
echo "<br>'a' valía 34, por lo que ahora le decrementamos 5<br>";
echo $a -= 5;
echo "<br>El valor de 'a' es:<br>";
echo $a;
echo "<br>Volvemos a decrementar en 5 'a' y multiplicamos x2<br>";
echo 2 * $a -= 5;
echo "<br>Ahora decrementamos en 5 'b', que valía 10 <br>";
echo $b -= 5;
echo "<br>Mostramos el valor de 'b'<br>";
echo $b;
echo "<br>Como originalmente era de tipo string, al multiplicarla nuevamente obtenemos 0<br>";
echo 2 * $b -= 5;
echo "<br><br>";
//probando operadores de post-incremento;
print_r("Probando el operadores de post-incremento");
echo "<br>La diferencia está en que, como primeramente le pedimos que muestre 'a' y luego la incrementea en 1, el incremento ahora no se ve reflejado<br>";
echo $a++;
echo "<br>Ahora pedimos que vuelva a imprimir 'a', y efectivamente la ha incrementado después de imprimirla arriba<br>";
echo $a;
echo "<br>Nuevamente ocurre lo mismo, ha multiplicado 2 x 'a' y justo ahí lo imprime, por lo que el incremento no se ve aquí reflejado<br>";
echo 2 * $a++;
echo "<br>Ahora, como ya habíamos incrementado 'a', al pedirle que multiplique de nuevo, el valor que coge es 26, y no 25<br>";
echo 2 * $a;
echo "<br>Ocurre lo mismo al decrementar, primero ha mostrado la variable y luego la ha decrementado<br>";
echo $a--;
echo "<br>Si volvemos a mostra 'a' vemos que el valor se ha reducido en 1 unidad<br>";
echo $a;
echo "<br>Más de lo mismo, multiplicamos 2 x 'a' antes de reducirle el valor, e imprimimos este resultado<br>";
echo 2 * $a--;
echo "<br>Pero, como habíamos reducido el valor de 'a', si le volvemos a pedir que la multiplique x 2, vemos que coge el valor que le habíamos dado antes<br>";
echo 2 * $a;